# Site settings
title: Kade Keith
email: keithkade@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Kade Keith
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kadekeith.me" # the base hostname & protocol for your site
twitter_username: Kade_Keith
github_username:  keithkade
collections:
- projects

# Build settings
markdown: kramdown
